### ISSUE TITLE
Why the exe is malicious? 

### ISSUE THREAD

**Issue by Rohamgames** [Genbox/VirusTotalContextMenu#12]
[here](https://www.virustotal.com/gui/file/53e384098eccb6029d2a2c716afa4807549821e38549eb961173c1bd6b55686c/detection) is the report of version 1.8.0
Why is it detected as hack tool?
![image](https://github.com/Genbox/VirusTotalContextMenu/assets/47294157/b33e6d3d-5e29-4d63-96f9-11046800c84d)
Also, here is the full graph:
![image](https://github.com/Genbox/VirusTotalContextMenu/assets/47294157/1a6db640-0df9-40fa-bc7c-72dcf978c8c9)

**Comment by Genbox** [comment]
Looks like Zillya is a crappy antivirus. My project is open source and can be compiled deterministic to the executable that is available for download. So, if in doubt, compile the code yourself and see that it matches the executable. There are no shenanigans here.

**Comment by Rohamgames** [comment]
I guess we are good then
Thanks for the response
