### ISSUE TITLE
I get an error when running

### ISSUE THREAD

**Issue by tyeeman** [Genbox/VirusTotalContextMenu#2]
Looks like a great app. I'm using Win7 64 bit. I run it and get this error - 

"You don't have access to the service. Make sure your API key is working correctly."

What do I do to fix it? I run also VTHash app and I did register an API key with that program but I don't see how to register my API key with this app??

**Comment by Genbox** [comment]
The API key has been revoked by VirusTotal. I'm going to remove it and let users supply their own.

**Comment by Genbox** [comment]
See the frontpage for the new instructions on how to run this application.

**Comment by tyeeman** [comment]
Thanks for this. Unfortunately I have no access to compilers.

**Comment by Genbox** [comment]
I upgraded the project to be .NET Core 2.0, but unfortunately, Microsoft in their infinite wisdom have decided to make packaging applications for deployment something to be left out. I can fiddle with it for a moment and update the instructions with a pre-compiled binary.

**Comment by Genbox** [comment]
https://github.com/Genbox/VirusTotalContextMenu/releases

I've uploaded version 1.6.0 - let me know how it works for you.

**Comment by tyeeman** [comment]
OK, thanks. After unpacking I get 100 files in the folder. Are they all necessary or were they used for compiling only?

**Comment by Genbox** [comment]
They are all necessary. It is a self-contained distribution that don't require .NET Core runtime to be installed on the machine. I can make a release that requires the runtime as well.

**Comment by Genbox** [comment]
According to https://github.com/dotnet/cli/issues/6237#issuecomment-328245453 they don't support exe files for framework dependent distributions. I can try to make a small .bat wrapper and see if that works.
