### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by ppvnf** [Genbox/VirusTotalContextMenu#4]
I would like to have VirusTotal integrated into Windows 11 new context menu, like NanaZip did. Also, is the 32 mb limitation still in place? Thanks!

**Comment by ppvnf** [comment]
I think this is abandonware. I hope I am wrong tho

**Comment by Genbox** [comment]
The articles I can find on Windows 11 context menu is a lot of MSI stuff and VC++. I'm not even going to attempt that.

**Comment by ppvnf** [comment]
That's unfortunate, but thanks for replying! Hopefully MS makes it easier in the future...
