### ISSUE TITLE
Result isn't displayed on Windows 11

### ISSUE THREAD

**Issue by ppvnf** [Genbox/VirusTotalContextMenu#6]
I tried the latest version on a Win11 PC and after the message below nothing is displayed
![Captura de tela 2022-11-12 165148](https://user-images.githubusercontent.com/73800734/201492154-8780c2ef-435f-4866-9502-69312e027249.png)

**Comment by Genbox** [comment]
Don't know why that is happening. Try the new [1.8.0 release](https://github.com/Genbox/VirusTotalContextMenu/releases/tag/v1.8.0) and see if that fixed the problem.

**Comment by ppvnf** [comment]
yes, it works now. thx
